concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: tests
env:
  GO111MODULE: on

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        # test both Go 1.26 and previous stable to check regression
        go-version: [1.25.x, 1.26.x]
        platform: [ubuntu-latest]
        include:
          - go-version: 1.26.x
            platform: windows-latest
          - go-version: 1.26.x
            platform: ubuntu-latest
            update-coverage: true

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: "**/go.sum"

      # =========================
      # DEBUG ENVIRONMENT SECTION
      # =========================
      - name: Debug Go and GCC environment
        run: |
          echo "=============================="
          echo "GO VERSION"
          echo "=============================="
          go version

          echo "=============================="
          echo "GO ENV"
          echo "=============================="
          go env

          echo "=============================="
          echo "WHICH GCC"
          echo "=============================="
          which gcc || true
          where gcc || true

          echo "=============================="
          echo "GCC VERSION"
          echo "=============================="
          gcc --version || true

          echo "=============================="
          echo "GCC LIBSYNC CHECK"
          echo "=============================="
          gcc --print-file-name libsynchronization.a || true

          echo "=============================="
          echo "PATH"
          echo "=============================="
          echo $PATH

      # =========================
      # RUN TESTS
      # =========================
      - name: Run go test
        run: |
          if [ -n "${{ matrix.update-coverage }}" ]; then
            script/test.sh -race -covermode atomic -coverprofile coverage.txt ./...
            exit
          fi
          script/test.sh -race -covermode atomic ./...

      - name: Ensure integration tests build
        run: go test -v -tags=integration -run=^$ ./test/integration

      - name: Upload coverage to Codecov
        if: ${{ matrix.update-coverage }}
        uses: codecov/codecov-action@v4
        with:
          use_oidc: true